# -*- coding: utf-8 -*-
"""Build a fully synthetic demo database so the boards render without scraping.

    python tools/make_demo_db.py            # create data/intel.db + fill it
    python tools/make_demo_db.py --fresh    # wipe an existing DB first
    python main.py serve                    # then open http://127.0.0.1:8765

Everything in here is FICTIONAL and generated from a fixed seed:
  * 6 countries (MX / BR / CO / CL / PE / AR - the codes the app already uses)
  * 8 brands: "Acme" (the placeholder own brand) + 7 invented rivals
  * 40 invented rival models (phones / tablets / earbuds / watches)
  * 12 invented retail channels (+ an "Acme Store" per own-pricing country)
  * ~60 days of daily price observations with promos, launches and rises,
    the derived price-move events, competitor matches, launch events,
    reviews with aspect tags, an intel feed, strategy signals, a watchlist
    with alerts and one facts-only weekly brief.

No real retailer, real brand (other than the "Acme" placeholder), real
product, real person or real company figure appears anywhere below. Prices
are plausible-looking round numbers, not observations of any market.

The script is deterministic for a given --seed and --end date. It reuses the
app's own schema/seed (app.db.init_db), product importer, competitor matcher,
alert scanner and weekly-report agent, so what you see is what the real
pipeline would produce - only the input rows are invented.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import random
import shutil
import sys
from datetime import date, datetime, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

try:                                    # cp936 consoles choke on UTF-8 output
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")   # type: ignore[attr-defined]
except Exception:                       # noqa: BLE001
    pass

# ---------------------------------------------------------------- config files

RUNTIME_DEMO_OVERRIDES = {
    # Nothing in the demo should reach the network or the OS.
    "schedule": {"enabled": False},
    "telegram": {"enabled": False},
    "phone_sync": {"enabled": 0},
    "weekly_report": {"auto": 0},
    "biweekly_pack": {"auto": 0},
    "archive": {"enabled": False},
    # runtime.example.yaml ships max_tokens as a placeholder string.
    "agents": {"max_tokens": 4096},
}


def _deep_merge(base: dict, override: dict) -> dict:
    out = dict(base)
    for k, v in (override or {}).items():
        if isinstance(v, dict) and isinstance(out.get(k), dict):
            out[k] = _deep_merge(out[k], v)
        else:
            out[k] = v
    return out


def ensure_config_files() -> list[str]:
    """Create config/runtime.yaml and config/my_products.csv when missing."""
    import yaml

    made = []
    cfg_dir = ROOT / "config"
    rt = cfg_dir / "runtime.yaml"
    if not rt.exists():
        example = cfg_dir / "runtime.example.yaml"
        base = {}
        if example.exists():
            with open(example, "r", encoding="utf-8") as f:
                base = yaml.safe_load(f) or {}
        merged = _deep_merge(base, RUNTIME_DEMO_OVERRIDES)
        with open(rt, "w", encoding="utf-8") as f:
            f.write("# Generated by tools/make_demo_db.py - demo settings, no tokens.\n"
                    "# Scheduling / Telegram / phone sync are OFF; turn them on only\n"
                    "# when you configure real credentials in the Settings page.\n")
            yaml.safe_dump(merged, f, allow_unicode=True, sort_keys=False)
        made.append(str(rt))

    csv_path = cfg_dir / "my_products.csv"
    if not csv_path.exists():
        example = cfg_dir / "my_products.example.csv"
        if example.exists():
            shutil.copyfile(example, csv_path)
            made.append(str(csv_path))
    return made


# ---------------------------------------------------------------- fictional universe

COUNTRIES = ["MX", "BR", "CO", "CL", "PE", "AR"]
CURRENCY = {"MX": "MXN", "BR": "BRL", "CO": "COP", "CL": "CLP", "PE": "PEN", "AR": "ARS"}
LANG = {"BR": "pt"}
# 1 USD = x local (round demo rates, drifted slightly per day below)
FX_BASE = {"MXN": 18.6, "BRL": 5.45, "COP": 4050.0, "CLP": 945.0, "PEN": 3.55, "ARS": 1350.0}
# how much pricier the same USD product lists locally (taxes / import duties)
COUNTRY_PREMIUM = {"MX": 1.00, "BR": 1.22, "CO": 1.05, "CL": 1.02, "PE": 1.04, "AR": 1.38}

RIVAL_BRANDS = ["Veltrix", "Orixa", "Nordlys", "Kaimo", "Solenne", "Zephyra", "Lumora"]

# (code, country, name, kind, default_seller_type, priority)
CHANNELS = [
    ("demo_andina",    "MX", "Andina Retail MX",  "retailer",    "official",    10),
    ("demo_plazanorte", "MX", "Plaza Norte",       "marketplace", "third_party", 20),
    ("demo_acme",      "MX", "Acme Store MX",     "brand_store", "official",     5),
    ("demo_condor",    "CO", "Bazar Condor",      "marketplace", "third_party", 20),
    ("demo_casaelec",  "CO", "Casa Electrica",    "retailer",    "official",    10),
    ("demo_acme",      "CO", "Acme Store CO",     "brand_store", "official",     5),
    ("demo_andina",    "CL", "Andina Retail CL",  "retailer",    "official",    10),
    ("demo_tiendasur", "CL", "TiendaSur",         "retailer",    "official",    12),
    ("demo_acme",      "CL", "Acme Store CL",     "brand_store", "official",     5),
    ("demo_plazanorte", "PE", "Plaza Norte PE",    "marketplace", "third_party", 20),
    ("demo_acme",      "PE", "Acme Store PE",     "brand_store", "official",     5),
    ("demo_horizonte", "BR", "Loja Horizonte",    "retailer",    "official",    10),
    ("demo_tropical",  "BR", "Bazar Tropical",    "marketplace", "third_party", 20),
    ("demo_condor",    "AR", "Bazar Condor AR",   "marketplace", "third_party", 20),
    ("demo_casaelec",  "AR", "Casa Electrica AR", "retailer",    "official",    10),
]

# 40 invented rival models: (brand, model_name, category, usd, ram, rom, screen, battery, camera, chipset, launch_offset_days)
# launch_offset_days: days before --end the model launched globally (None = long ago)
RIVAL_MODELS = [
    # phones (16)
    ("Veltrix", "Kestrel 9",          "phone",   320, 8,  128, 6.6, 5000, 50, "Kestrel Core K9",   None),
    ("Veltrix", "Kestrel 9 Pro",      "phone",   540, 12, 256, 6.7, 5100, 64, "Kestrel Core K9X",  None),
    ("Veltrix", "Kestrel 10",         "phone",   380, 8,  256, 6.6, 5200, 50, "Kestrel Core K10",  35),
    ("Orixa",   "Tundra X2",          "phone",   260, 6,  128, 6.5, 5000, 48, "Orion T2",          None),
    ("Orixa",   "Tundra X3",          "phone",   290, 8,  128, 6.6, 5000, 50, "Orion T3",          20),
    ("Orixa",   "Tundra Ultra",       "phone",   890, 16, 512, 6.8, 5400, 200, "Orion U1",         None),
    ("Nordlys", "Fjell 5",            "phone",   210, 6,  128, 6.4, 4800, 48, "Fjell Chip F5",     None),
    ("Nordlys", "Fjell 5 Plus",       "phone",   330, 8,  256, 6.7, 5000, 50, "Fjell Chip F5+",    None),
    ("Kaimo",   "Ripple 30",          "phone",   190, 4,  128, 6.5, 5000, 50, "Ripple R30",        None),
    ("Kaimo",   "Ripple 30 Lite",     "phone",   150, 4,  64,  6.4, 5000, 13, "Ripple R30L",       None),
    ("Kaimo",   "Ripple 40",          "phone",   240, 8,  256, 6.6, 5000, 50, "Ripple R40",        60),
    ("Solenne", "Aurum S1",           "phone",   720, 12, 256, 6.7, 4700, 50, "Aurum A1",          None),
    ("Solenne", "Aurum S1 Max",       "phone",   950, 16, 512, 6.9, 5000, 200, "Aurum A1",         None),
    ("Zephyra", "Breeze 7",           "phone",   280, 8,  128, 6.5, 5000, 64, "Zephyr Z7",         None),
    ("Zephyra", "Breeze 7 Neo",       "phone",   350, 8,  256, 6.7, 5000, 108, "Zephyr Z7N",       45),
    ("Lumora",  "Prism P20",          "phone",   410, 8,  256, 6.7, 5000, 50, "Prism Core P20",    None),
    # tablets (8)
    ("Veltrix", "Kestrel Tab 11",     "tablet",  330, 8,  128, 11.0, 8000, 13, "Kestrel Core K9",  None),
    ("Orixa",   "Tundra Pad 10",      "tablet",  220, 6,  128, 10.4, 7700, 8,  "Orion T2",         None),
    ("Orixa",   "Tundra Pad 12 Pro",  "tablet",  600, 12, 256, 12.4, 10000, 13, "Orion U1",        30),
    ("Nordlys", "Fjell Tab 10",       "tablet",  180, 4,  64,  10.1, 7000, 8,  "Fjell Chip F5",    None),
    ("Kaimo",   "Ripple Pad 11",      "tablet",  200, 6,  128, 11.0, 8000, 8,  "Ripple R40",       None),
    ("Solenne", "Aurum Slate 11",     "tablet",  520, 8,  256, 11.0, 8500, 12, "Aurum A1",         None),
    ("Zephyra", "Breeze Pad 10",      "tablet",  250, 8,  128, 10.6, 8000, 13, "Zephyr Z7",        None),
    ("Lumora",  "Prism Tab 11",       "tablet",  310, 8,  256, 11.0, 8300, 13, "Prism Core P20",   None),
    # audio (8)
    ("Veltrix", "Kestrel Buds 3",     "audio",   90,  None, None, None, None, None, None,          None),
    ("Orixa",   "Tundra Buds Pro",    "audio",   140, None, None, None, None, None, None,          25),
    ("Nordlys", "Fjell Pods 2",       "audio",   60,  None, None, None, None, None, None,          None),
    ("Kaimo",   "Ripple Buds Lite",   "audio",   40,  None, None, None, None, None, None,          None),
    ("Solenne", "Aurum Buds",         "audio",   220, None, None, None, None, None, None,          None),
    ("Zephyra", "Breeze Buds 2",      "audio",   75,  None, None, None, None, None, None,          None),
    ("Lumora",  "Prism Pods",         "audio",   110, None, None, None, None, None, None,          None),
    ("Lumora",  "Prism Pods ANC",     "audio",   160, None, None, None, None, None, None,          50),
    # wearables (8)
    ("Veltrix", "Kestrel Watch 4",    "wearable", 240, None, None, 1.43, 450, None, None,          None),
    ("Orixa",   "Tundra Watch S",     "wearable", 180, None, None, 1.39, 400, None, None,          None),
    ("Nordlys", "Fjell Band 6",       "wearable", 60,  None, None, 1.47, 180, None, None,          None),
    ("Kaimo",   "Ripple Band 3",      "wearable", 45,  None, None, 1.47, 180, None, None,          None),
    ("Solenne", "Aurum Watch",        "wearable", 300, None, None, 1.45, 420, None, None,          15),
    ("Zephyra", "Breeze Fit 2",       "wearable", 110, None, None, 1.60, 300, None, None,          None),
    ("Lumora",  "Prism Watch 2",      "wearable", 200, None, None, 1.43, 400, None, None,          None),
    ("Lumora",  "Prism Band",         "wearable", 55,  None, None, 1.47, 180, None, None,          None),
]

# Own-brand models that get observations (names must exist in my_products.csv).
# (marketing_name, usd, ram, rom, screen_text)
OWN_MODELS = [
    ("ACME Nimbus 60",               300, 8,  128, "6.6 inch OLED"),
    ("ACME Vega 61 Pro",             560, 12, 256, "6.7 inch OLED 120Hz"),
    ("ACME Nimbus 62 Lite",          200, 6,  128, "6.5 inch LCD"),
    ("ACME Vega 63 Max",             900, 16, 512, "6.8 inch OLED 120Hz"),
    ("ACME Slate 10 2024 R1",        210, 6,  128, "10.4 inch LCD"),
    ("ACME Slate 11 Pro 2024 R2",    520, 8,  256, "11 inch OLED"),
    ("ACME Slate 12 Air 2024 R3",    330, 8,  128, "11 inch LCD 90Hz"),
    ("ACME SonicBuds 2 Pro",         130, None, None, None),
    ("ACME SonicArc 1",              85,  None, None, None),
    ("ACME SonicBuds 3 SE",          45,  None, None, None),
    ("WATCH GT 6",                   230, None, None, "1.43 inch AMOLED"),
    ("ACME Watch Fit 7 Active v2",   105, None, None, "1.6 inch AMOLED"),
]

COLORS = ["Negro", "Azul", "Blanco", "Verde", "Gris"]
COLORS_PT = {"Negro": "Preto", "Azul": "Azul", "Blanco": "Branco", "Verde": "Verde", "Gris": "Cinza"}

# Review snippets tagged by aspect: (aspect_code, sentiment, es, pt, zh)
SNIPPETS = [
    ("battery", "positive", "La bateria dura dos dias sin problema.", "A bateria dura dois dias tranquilo.", "电池能撑两天，没问题。"),
    ("battery", "negative", "La bateria se agota antes de terminar el dia.", "A bateria acaba antes do fim do dia.", "电池一天都撑不到。"),
    ("camera", "positive", "Las fotos de dia salen muy nitidas.", "As fotos de dia saem muito nitidas.", "白天拍照非常清晰。"),
    ("camera", "negative", "De noche la camara mete mucho ruido.", "A noite a camera tem muito ruido.", "夜拍噪点很多。"),
    ("screen", "positive", "La pantalla es brillante y fluida.", "A tela e brilhante e fluida.", "屏幕明亮流畅。"),
    ("screen", "negative", "La pantalla se ve apagada bajo el sol.", "A tela fica escura no sol.", "阳光下屏幕偏暗。"),
    ("performance", "positive", "Va rapido con todas las apps.", "Roda rapido com todos os apps.", "所有应用都跑得很快。"),
    ("performance", "negative", "Se traba al abrir varias apps.", "Trava ao abrir varios apps.", "多开应用会卡顿。"),
    ("heat", "negative", "Se calienta bastante jugando.", "Esquenta bastante jogando.", "玩游戏发热明显。"),
    ("build", "positive", "Se siente solido y bien terminado.", "Parece solido e bem acabado.", "手感扎实做工好。"),
    ("build", "negative", "El plastico se raya facil.", "O plastico risca facil.", "塑料容易刮花。"),
    ("software", "positive", "El sistema es limpio y sin publicidad.", "O sistema e limpo e sem propaganda.", "系统干净无广告。"),
    ("software", "negative", "Trae demasiadas apps preinstaladas.", "Vem com apps demais pre-instalados.", "预装软件太多。"),
    ("sound", "positive", "El sonido es claro con buenos graves.", "O som e claro com bons graves.", "音质清晰低音好。"),
    ("sound", "negative", "Los agudos suenan metalicos.", "Os agudos soam metalicos.", "高音发尖。"),
    ("noise_cancel", "positive", "La cancelacion de ruido funciona muy bien en el bus.", "O cancelamento de ruido funciona bem no onibus.", "降噪在公交上效果很好。"),
    ("noise_cancel", "negative", "La cancelacion de ruido apenas se nota.", "O cancelamento de ruido quase nao se nota.", "降噪几乎感觉不到。"),
    ("comfort", "positive", "Comodos incluso despues de horas.", "Confortaveis mesmo depois de horas.", "戴几个小时也舒服。"),
    ("comfort", "negative", "Se caen al correr.", "Caem quando corro.", "跑步会掉。"),
    ("connectivity", "positive", "Se conecta al instante.", "Conecta na hora.", "连接很快。"),
    ("connectivity", "negative", "Se desconecta del bluetooth cada tanto.", "Desconecta do bluetooth de vez em quando.", "蓝牙时不时断开。"),
    ("design", "positive", "El diseno es elegante y liviano.", "O design e elegante e leve.", "设计优雅轻薄。"),
    ("health", "positive", "El monitor de sueno es bastante preciso.", "O monitor de sono e bem preciso.", "睡眠监测挺准。"),
    ("health", "negative", "El conteo de pasos es exagerado.", "A contagem de passos e exagerada.", "计步偏多。"),
    ("storage", "negative", "Los 64GB se llenan enseguida.", "Os 64GB enchem rapido.", "64GB 很快就满了。"),
    ("price", "positive", "Excelente relacion precio calidad.", "Otimo custo beneficio.", "性价比很高。"),
    ("price", "negative", "Caro para lo que ofrece.", "Caro pelo que oferece.", "这价格不值。"),
    ("logistics", "positive", "Llego en dos dias, bien embalado.", "Chegou em dois dias, bem embalado.", "两天就到，包装好。"),
    ("logistics", "negative", "Tardo dos semanas en llegar.", "Demorou duas semanas para chegar.", "等了两周才到。"),
    ("service", "negative", "El servicio tecnico no responde.", "A assistencia tecnica nao responde.", "售后不回复。"),
    ("packaging", "negative", "No trae cargador en la caja.", "Nao vem carregador na caixa.", "盒子里没有充电器。"),
    ("authenticity", "positive", "Producto original, sellado.", "Produto original, lacrado.", "正品，密封完好。"),
]

NEWS_OUTLETS = ["Tecnoprensa Andina", "Diario Digital Tropical", "El Semanario Movil",
                "Portal Gadget Sur", "Boletim Tech Horizonte"]

# (tag, importance, es title template, zh summary template)
NEWS_TEMPLATES = [
    ("新品", 5, "{brand} presenta el {model} en {country}", "{brand} 在{country_zh}发布 {model}，主打{cat_zh}中端市场。"),
    ("新品", 4, "{brand} confirma la llegada del {model} a America Latina", "{brand} 确认 {model} 将登陆拉美，首批国家含{country_zh}。"),
    ("促销", 3, "{channel} lanza semana de descuentos en {cat_es} {brand}", "{channel} 对 {brand} {cat_zh}开启折扣周，力度约 {pct}%。"),
    ("促销", 2, "{brand} baja el precio del {model} en {country}", "{brand} 在{country_zh}下调 {model} 售价约 {pct}%。"),
    ("渠道", 3, "{brand} amplia su presencia en {channel}", "{brand} 扩大在 {channel} 的铺货，新增 {cat_zh}品类。"),
    ("广告", 2, "{brand} inicia campana de marketing para el {model}", "{brand} 为 {model} 启动营销活动，聚焦{cat_zh}。"),
    ("其他", 1, "Analistas destacan el crecimiento de {brand} en {cat_es}", "分析师关注 {brand} 在{cat_zh}品类的增长。"),
]

CAT_ES = {"phone": "celulares", "tablet": "tablets", "audio": "audifonos", "wearable": "smartwatches"}
CAT_ZH = {"phone": "手机", "tablet": "平板", "audio": "音频", "wearable": "穿戴"}
COUNTRY_ZH = {"MX": "墨西哥", "BR": "巴西", "CO": "哥伦比亚", "CL": "智利", "PE": "秘鲁", "AR": "阿根廷"}
COUNTRY_ES = {"MX": "Mexico", "BR": "Brasil", "CO": "Colombia", "CL": "Chile", "PE": "Peru", "AR": "Argentina"}

SIGNAL_TEMPLATES = [
    ("clearance", "{brand} {model} 在{country_zh}连续两周降价，疑似为下一代清库。", "我方同档产品的价格优势正在缩小。", "关注该机型库存与新品发布节奏，暂不跟降。"),
    ("promo_prep", "{brand} 在{country_zh}的{cat_zh}折扣覆盖率明显上升。", "促销期内我方转化可能受挤压。", "评估是否同步配置限时促销。"),
    ("price_war", "{country_zh}{cat_zh}品类三个品牌同周降价超过 8%。", "价格带整体下移，我方中端产品定位受压。", "优先保住主销款价格锚点，避免全线跟随。"),
    ("restore", "{brand} {model} 促销结束后价格回到原位。", "对手促销为阶段性动作，不是长期定价调整。", "无需调整定价，继续观察。"),
    ("new_launch_premium", "{brand} {model} 在{country_zh}以高于系列前代 12% 的价格上市。", "对手上探价格带，为我方旗舰留出空间。", "强化旗舰款的规格对比传播。"),
    ("cost_hike", "{brand} 在{country_zh}上调多款{cat_zh}售价 5%~9%。", "汇率与成本压力传导至终端价。", "评估我方在该国的涨价窗口。"),
]


# ---------------------------------------------------------------- helpers

def md5(*parts) -> str:
    return hashlib.md5("|".join("" if p is None else str(p) for p in parts).encode("utf-8")).hexdigest()


def round_local(v: float, cur: str) -> float:
    """Round to the kind of numbers shelves show (x,990 / x99 / x.9)."""
    if cur in ("CLP", "COP", "ARS"):
        return float(int(v / 1000) * 1000 + 990) if v >= 5000 else float(int(v / 100) * 100 + 90)
    if cur in ("MXN", "BRL"):
        return float(int(v / 10) * 10 + 9)
    return round(v, 1) if v < 100 else float(int(v) - 0.1) if int(v) % 2 else float(int(v) + 0.9)


def installments_text(price: float, cur: str, n: int = 12) -> str:
    return f"{n} x {price / n:,.0f} {cur} sin interes"


def sku_key(ram, rom, color) -> str:
    return f"{ram or 0}+{rom or 0}/{(color or '').lower()}"


def title_for(brand: str, model: str, cat: str, ram, rom, color, lang: str) -> str:
    col = COLORS_PT.get(color, color) if lang == "pt" else color
    if cat in ("phone", "tablet") and ram and rom:
        return f"{brand} {model} {ram}GB+{rom}GB {col}"
    if cat == "phone":
        return f"Celular {brand} {model} {col}"
    if cat == "tablet":
        return f"Tablet {brand} {model} {col}"
    if cat == "audio":
        return f"Audifonos {brand} {model} {col}" if lang != "pt" else f"Fone {brand} {model} {col}"
    return f"Smartwatch {brand} {model} {col}"


# ---------------------------------------------------------------- generator

class DemoBuilder:
    def __init__(self, seed: int, end: date, days: int):
        self.rng = random.Random(seed)
        self.end = end
        self.days = days
        self.start = end - timedelta(days=days - 1)
        self.dates = [(self.start + timedelta(days=i)).isoformat() for i in range(days)]
        self.fx: dict[str, dict[str, float]] = {}      # date -> currency -> rate
        self.channel_ids: dict[tuple[str, str], int] = {}
        self.channel_meta: dict[int, dict] = {}
        self.brand_ids: dict[str, int] = {}
        self.rival_ids: list[int] = []
        self.rival_meta: dict[int, dict] = {}
        self.own_ids: list[int] = []
        self.own_meta: dict[int, dict] = {}
        self.run_ids: dict[str, int] = {}
        self.first_seen: dict[tuple[int, str], tuple[str, float, str, int]] = {}
        self.urls_by_product: dict[int, list[tuple[str, str, int]]] = {}   # pid -> [(url, cc, channel_id)]
        self.counts: dict[str, int] = {}

    # ------------------------------------------------ dimensions

    def dims(self, db) -> None:
        with db.tx() as conn:
            for b in RIVAL_BRANDS:
                conn.execute("""INSERT INTO brand(name,aliases,is_ours)
                                VALUES(?,?,0) ON CONFLICT(name) DO NOTHING""",
                             (b, json.dumps([b])))
            for code, cc, name, kind, seller, prio in CHANNELS:
                conn.execute("""
                    INSERT INTO channel(code,country_code,name,kind,base_url,search_url,
                                        adapter,default_seller_type,priority,enabled,notes)
                    VALUES(?,?,?,?,?,?,'generic',?,?,1,'demo channel (fictional)')
                    ON CONFLICT(code,country_code) DO UPDATE SET
                      name=excluded.name, kind=excluded.kind, enabled=1
                """, (code, cc, name, kind, f"https://{code}.example.invalid",
                      f"https://{code}.example.invalid/search?q={{q}}", seller, prio))
        for r in db.q("SELECT id,name,is_ours FROM brand"):
            self.brand_ids[r["name"]] = r["id"]
        own = [r for r in db.q("SELECT id,name FROM brand WHERE is_ours=1")]
        if not own:
            raise SystemExit("brands.yaml has no is_ours brand - cannot build demo")
        self.own_brand = own[0]["name"]
        self.own_brand_id = own[0]["id"]
        for r in db.q("SELECT id,code,country_code,name,kind FROM channel WHERE code LIKE 'demo_%'"):
            self.channel_ids[(r["code"], r["country_code"])] = r["id"]
            self.channel_meta[r["id"]] = dict(r)
        # daily FX with a gentle drift
        drift = {c: 0.0 for c in FX_BASE}
        for d in self.dates:
            row = {}
            for cur, base in FX_BASE.items():
                drift[cur] += self.rng.uniform(-0.002, 0.0025)
                row[cur] = round(base * (1 + drift[cur]), 4)
            self.fx[d] = row
        with db.tx() as conn:
            for d, row in self.fx.items():
                for cur, rate in row.items():
                    conn.execute("""INSERT OR REPLACE INTO fx_rate(rate_date,currency,rate,source)
                                    VALUES(?,?,?,'demo-synthetic')""", (d, cur, rate))

    # ------------------------------------------------ products

    def products(self, db, products_mod) -> None:
        rep = products_mod.import_product_list()
        if rep.get("error"):
            print("  ! my_products.csv:", rep["error"])
        else:
            print(f"  own catalog: {rep['total']} rows ({rep['created']} new)")
        with db.tx() as conn:
            for brand, model, cat, usd, ram, rom, screen, batt, cam, chip, launch_off in RIVAL_MODELS:
                key = "".join(ch for ch in model.lower() if ch.isalnum())
                launch = None
                if launch_off is not None:
                    launch = (self.end - timedelta(days=launch_off)).isoformat()
                else:
                    launch = (self.end - timedelta(days=self.rng.randint(240, 700))).isoformat()
                conn.execute("""
                    INSERT INTO rival_product(brand_id,category_code,model_name,model_key,series,
                        ram_gb,rom_gb,chipset,screen_size,battery_mah,camera_main_mp,os,
                        spec_source,spec_confidence,global_launch_date,name_verified,name_source)
                    VALUES(?,?,?,?,?,?,?,?,?,?,?,?,'demo-synthetic',1.0,?,1,'demo')
                    ON CONFLICT(brand_id,model_key,category_code) DO UPDATE SET
                      global_launch_date=excluded.global_launch_date
                """, (self.brand_ids[brand], cat, model, key, model.split()[0], ram, rom, chip,
                      screen, batt, cam, "DemoOS" if cat in ("phone", "tablet") else None, launch))
        for r in db.q("""SELECT rp.*, b.name AS brand FROM rival_product rp
                         JOIN brand b ON b.id=rp.brand_id WHERE rp.spec_source='demo-synthetic'
                         ORDER BY rp.id"""):
            spec = next((m for m in RIVAL_MODELS if m[0] == r["brand"] and m[1] == r["model_name"]), None)
            if not spec:
                continue
            self.rival_ids.append(r["id"])
            self.rival_meta[r["id"]] = {**dict(r), "usd": spec[3], "launch_off": spec[10]}
        # own models: attach specs + one SKU so the matcher can compare
        for name, usd, ram, rom, screen in OWN_MODELS:
            rows = db.q("SELECT id, category_code FROM my_product WHERE marketing_name=?", (name,))
            if not rows:
                print(f"  ! own model not in my_products.csv, skipped: {name}")
                continue
            with db.tx() as conn:
                for r in rows:
                    conn.execute("UPDATE my_product SET screen=?, chipset=? WHERE id=?",
                                 (screen, "Acme Core X1" if ram else None, r["id"]))
                    if ram:
                        conn.execute("""INSERT INTO my_sku(product_id,sku_name,color,ram_gb,rom_gb)
                                        VALUES(?,?,?,?,?)
                                        ON CONFLICT DO NOTHING""",
                                     (r["id"], "SKU1", "Negro", ram, rom))
                    self.own_ids.append(r["id"])
                    self.own_meta[r["id"]] = {"name": name, "usd": usd, "ram": ram, "rom": rom,
                                              "cat": r["category_code"]}

    # ------------------------------------------------ price series

    def _plan_series(self, usd: float, launch_off, cc: str) -> list[float | None]:
        """Daily multiplier on the base price (None = not on shelf yet)."""
        n = self.days
        rng = self.rng
        mult = [1.0] * n
        appear = 0
        if launch_off is not None:
            appear = max(0, n - launch_off - rng.randint(0, 6))   # on shelf a few days after global launch
            for i in range(appear, min(n, appear + rng.randint(8, 16))):
                mult[i] = 1.08                                     # launch premium
        # 0-2 promo windows
        for _ in range(rng.choice([0, 0, 1, 1, 2])):
            s = rng.randint(appear, max(appear, n - 6))
            length = rng.randint(4, 12)
            off = rng.choice([0.05, 0.06, 0.08, 0.10, 0.12, 0.15, 0.18, 0.22, 0.25])
            for i in range(s, min(n, s + length)):
                mult[i] = min(mult[i], 1.0 - off)
        # occasional permanent rise or cut (step)
        # one permanent step (rise or cut) on ~36% of lines - the factor is drawn ONCE,
        # otherwise every day after the step would re-roll and look like daily jitter
        roll = rng.random()
        if roll < 0.36:
            s = rng.randint(appear + 5, n - 1) if n - 1 > appear + 5 else n - 1
            step = rng.choice([1.05, 1.07, 1.09, 1.12]) if roll < 0.18 else rng.choice([0.93, 0.95, 0.96])
            for i in range(s, n):
                mult[i] = mult[i] * step
        # mark days before launch as absent
        return [None if i < appear else round(m, 4) for i, m in enumerate(mult)]

    def _runs(self, db) -> None:
        """One scrape run per day so the runs page and overview have history."""
        with db.tx() as conn:
            for d in self.dates:
                started = f"{d} 07:30:00"
                cur = conn.execute("""INSERT INTO scrape_run(started_at,finished_at,run_date,mode,scope,status)
                                      VALUES(?,?,?,?,?,'ok')""",
                                   (started, f"{d} 09:{self.rng.randint(10, 55):02d}:00", d, "daily",
                                    json.dumps({"demo": True, "countries": COUNTRIES})))
                self.run_ids[d] = cur.lastrowid
        self.counts["scrape_run"] = len(self.run_ids)

    def observations(self, db) -> None:
        self._runs(db)
        rng = self.rng
        rows: list[tuple] = []
        units: dict[tuple[str, int], list[int]] = {}
        moves: list[tuple] = []
        unit_meta: dict[tuple[str, int], tuple] = {}

        def add_obs(d, cc, ch_id, brand_id, cat, rival_pid, my_pid, title, model_guess, ram, rom,
                    color, list_p, sale_p, seller_name, seller_type, seller_kind, product_kind,
                    url, in_stock=1, audit="accepted", audit_reason=None, condition="new"):
            cur = CURRENCY[cc]
            fx = self.fx[d][cur]
            disc = round((list_p - sale_p) / list_p * 100, 1) if list_p and list_p > sale_p else 0.0
            rows.append((
                d, f"{d} 08:{rng.randint(0, 59):02d}:{rng.randint(0, 59):02d}", cc, ch_id, brand_id, cat,
                rival_pid, my_pid, title, model_guess, ram, rom, color, list_p, sale_p, cur, fx,
                round(sale_p / fx, 2), installments_text(sale_p, cur), seller_name, seller_type,
                seller_kind, product_kind, disc, in_stock, condition, audit, audit_reason,
                "rule:demo" if audit != "pending" else None, url,
                md5(d, ch_id, url, sale_p, seller_kind), self.run_ids[d]))
            units.setdefault((d, ch_id), []).append(1)
            unit_meta[(d, ch_id)] = (cc, brand_id, cat)

        # ---- rival products
        for pid in self.rival_ids:
            m = self.rival_meta[pid]
            brand, model, cat, usd = m["brand"], m["model_name"], m["category_code"], m["usd"]
            ccs = rng.sample(COUNTRIES, rng.randint(5, 6))
            ccs.sort(key=COUNTRIES.index)
            for cc in ccs:
                chans = [cid for (code, c2), cid in self.channel_ids.items()
                         if c2 == cc and self.channel_meta[cid]["kind"] != "brand_store"]
                chans = sorted(rng.sample(chans, rng.randint(1, len(chans))))
                cur = CURRENCY[cc]
                base_local = usd * FX_BASE[cur] * COUNTRY_PREMIUM[cc]
                lang = LANG.get(cc, "es")
                variants = [(m["ram_gb"], m["rom_gb"], "Negro")]
                if cat in ("phone", "tablet") and rng.random() < 0.5 and m["rom_gb"]:
                    variants.append((m["ram_gb"], m["rom_gb"] * 2, "Azul"))
                for ch_id in chans:
                    meta = self.channel_meta[ch_id]
                    mp_ = meta["kind"] == "marketplace"
                    series = self._plan_series(usd, m["launch_off"], cc)
                    ch_prem = rng.uniform(0.97, 1.06)
                    skip_days = set(rng.sample(range(self.days), rng.randint(0, 4)))
                    for vi, (ram, rom, color) in enumerate(variants):
                        var_mult = 1.0 if vi == 0 else 1.18
                        url = f"https://{meta['code']}.example.invalid/{cc.lower()}/p/{pid}-{vi}"
                        self.urls_by_product.setdefault(pid, []).append((url, cc, ch_id))
                        list_base = round_local(base_local * ch_prem * var_mult, cur)
                        prev = None
                        sellers = [("self_operated", meta["name"], "official", 1.0)]
                        if mp_:
                            sellers = [("brand_official", f"{brand} Tienda Oficial", "official", 1.0),
                                       ("third_party", f"Vendedor {rng.randint(100, 999)}", "third_party",
                                        rng.choice([0.96, 0.98, 1.03, 1.06, 1.10]))]
                        for i, d in enumerate(self.dates):
                            mul = series[i]
                            if mul is None or (i in skip_days and i != self.days - 1):
                                continue
                            for sk, sname, stype, sprem in sellers:
                                sale = round_local(list_base * mul * sprem, cur)
                                listp = max(list_base, sale)
                                col = color if sk != "third_party" else "Gris"
                                title = title_for(brand, model, cat, ram, rom, col, lang)
                                add_obs(d, cc, ch_id, self.brand_ids[brand], cat, pid, None, title,
                                        model, ram, rom, col, listp, sale, sname, stype, sk, "device",
                                        url if sk != "third_party" else url + "?seller=3p")
                                if sk != "third_party":
                                    if (pid, cc) not in self.first_seen:
                                        self.first_seen[(pid, cc)] = (d, sale, cur, ch_id)
                                    if prev is not None and prev[1] != sale:
                                        pct = round((sale - prev[1]) / prev[1] * 100, 2)
                                        moves.append((d, cc, ch_id, self.brand_ids[brand], cat, pid,
                                                      sku_key(ram, rom, color), prev[1], sale, pct,
                                                      "up" if pct > 0 else "down", prev[0],
                                                      (date.fromisoformat(d) - date.fromisoformat(prev[0])).days,
                                                      1 if sk in ("self_operated", "brand_official") else 0, cur))
                                    prev = (d, sale)
                    # a stray accessory listing so the audit gate has something to reject
                    if rng.random() < 0.25:
                        d = self.dates[-1]
                        acc_price = round_local(base_local * 0.04, cur)
                        add_obs(d, cc, ch_id, self.brand_ids[brand], cat, None, None,
                                f"Funda protectora para {brand} {model}", None, None, None, None,
                                acc_price, acc_price, meta["name"], "official", "self_operated",
                                "accessory", f"https://{meta['code']}.example.invalid/{cc.lower()}/acc/{pid}",
                                audit="rejected", audit_reason="accessory below category price floor")

        # ---- own brand (Acme) in its stores + one retailer per country
        for pid in self.own_ids:
            m = self.own_meta[pid]
            for cc in ("MX", "CO", "CL", "PE"):
                store = self.channel_ids.get(("demo_acme", cc))
                retail = [cid for (code, c2), cid in self.channel_ids.items()
                          if c2 == cc and self.channel_meta[cid]["kind"] == "retailer"]
                chans = [store] + (retail[:1] if retail else [])
                cur = CURRENCY[cc]
                base_local = m["usd"] * FX_BASE[cur] * COUNTRY_PREMIUM[cc]
                for ch_id in chans:
                    meta = self.channel_meta[ch_id]
                    series = self._plan_series(m["usd"], None, cc)
                    list_base = round_local(base_local * (1.0 if meta["kind"] == "brand_store" else rng.uniform(0.99, 1.05)), cur)
                    url = f"https://{meta['code']}.example.invalid/{cc.lower()}/own/{pid}"
                    title = f"{m['name']} {m['ram']}GB+{m['rom']}GB Negro" if m["ram"] else f"{m['name']} Negro"
                    for i, d in enumerate(self.dates):
                        if series[i] is None:
                            continue
                        sale = round_local(list_base * series[i], cur)
                        add_obs(d, cc, ch_id, self.own_brand_id, m["cat"], None, pid, title, m["name"],
                                m["ram"], m["rom"], "Negro", max(list_base, sale), sale, meta["name"],
                                "official", "self_operated", "device", url)

        # a small pending backlog so the "awaiting audit" notes are exercised
        n_pending = max(1, len(rows) // 60)
        for idx in rng.sample(range(len(rows)), n_pending):
            r = list(rows[idx])
            if r[6] is not None and r[26] == "accepted":
                r[26], r[28] = "pending", None
                rows[idx] = tuple(r)

        with db.tx() as conn:
            conn.executemany("""
                INSERT OR IGNORE INTO price_obs(obs_date,captured_at,country_code,channel_id,brand_id,
                    category_code,rival_product_id,my_product_id,title,model_guess,ram_gb,rom_gb,color,
                    list_price,sale_price,currency,fx_rate,sale_price_usd,installments,seller_name,
                    seller_type,seller_kind,product_kind,discount_pct,is_in_stock,condition,
                    audit_status,audit_reason,audit_by,url,row_hash,run_id)
                VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
            """, rows)
            conn.executemany("""
                INSERT OR IGNORE INTO price_move(move_date,country_code,channel_id,brand_id,category_code,
                    rival_product_id,sku_key,prev_price,curr_price,change_pct,direction,prev_date,
                    days_span,is_official,currency)
                VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
            """, moves)
            for (d, ch_id), items in sorted(units.items()):
                cc, brand_id, cat = unit_meta[(d, ch_id)]
                conn.execute("""INSERT INTO scrape_unit(run_id,channel_id,country_code,brand_id,category_code,
                                    query,status,engine,items,duration_ms,message,created_at)
                                VALUES(?,?,?,?,?,?,?,?,?,?,?,?)""",
                             (self.run_ids[d], ch_id, cc, None, None, "demo sweep", "ok", "demo",
                              len(items), rng.randint(4000, 40000), None, f"{d} 08:30:00"))
            conn.execute("""UPDATE scrape_run SET pages_ok=(SELECT COUNT(*) FROM scrape_unit su WHERE su.run_id=scrape_run.id),
                            rows_written=(SELECT COALESCE(SUM(items),0) FROM scrape_unit su WHERE su.run_id=scrape_run.id)""")
            for ch_id, meta in self.channel_meta.items():
                conn.execute("""INSERT OR REPLACE INTO channel_health(channel_id,check_date,attempts,ok_count,
                                    empty_count,blocked_count,failed_count,avg_items,avg_duration_ms,
                                    health_score,verdict,suggested_action)
                                VALUES(?,?,?,?,?,?,?,?,?,?,?,?)""",
                             (ch_id, self.dates[-1], 7, 7, 0, 0, 0, rng.randint(20, 60),
                              rng.randint(6000, 30000), 1.0, "healthy", "continue"))
        self.counts["price_obs"] = len(rows)
        self.counts["price_move"] = len(moves)

    # ------------------------------------------------ launches

    def launches(self, db) -> None:
        rng = self.rng
        n = 0
        with db.tx() as conn:
            for pid in self.rival_ids:
                m = self.rival_meta[pid]
                launch = m["global_launch_date"]
                if m["launch_off"] is not None:
                    conn.execute("""INSERT OR IGNORE INTO launch_event(rival_product_id,brand_id,country_code,
                                        event_type,event_date,detected_by,confidence,notes)
                                    VALUES(?,?,NULL,'global_launch',?,'demo-synthetic',1.0,'fictional launch')""",
                                 (pid, m["brand_id"], launch))
                    n += 1
                seen = sorted(((cc, v) for (p, cc), v in self.first_seen.items() if p == pid),
                              key=lambda kv: kv[1][0])
                for rank, (cc, (d, price, cur, ch_id)) in enumerate(seen, 1):
                    if m["launch_off"] is None and rng.random() < 0.7:
                        continue            # old models: mostly no fresh availability event
                    lag = (date.fromisoformat(d) - date.fromisoformat(launch)).days
                    conn.execute("""INSERT OR IGNORE INTO launch_event(rival_product_id,brand_id,country_code,
                                        event_type,event_date,first_seen_price,currency,first_seen_usd,channel_id,
                                        days_after_global,country_rank,detected_by,confidence)
                                    VALUES(?,?,?,'country_available',?,?,?,?,?,?,?,'scraper',1.0)""",
                                 (pid, m["brand_id"], cc, d, price, cur, round(price / self.fx[d][cur], 2),
                                  ch_id, lag, rank))
                    n += 1
        self.counts["launch_event"] = n

    # ------------------------------------------------ intel + signals

    def intel(self, db) -> None:
        rng = self.rng
        n = 0
        with db.tx() as conn:
            for i in range(36):
                pid = rng.choice(self.rival_ids)
                m = self.rival_meta[pid]
                cc = rng.choice(COUNTRIES)
                tag, imp, t_es, s_zh = rng.choice(NEWS_TEMPLATES)
                ch = rng.choice([c for c in CHANNELS if c[1] == cc])[2]
                ctx = dict(brand=m["brand"], model=m["model_name"], country=COUNTRY_ES[cc],
                           country_zh=COUNTRY_ZH[cc], cat_es=CAT_ES[m["category_code"]],
                           cat_zh=CAT_ZH[m["category_code"]], channel=ch, pct=rng.choice([8, 10, 12, 15, 20]))
                age = rng.randint(0, 6) if i < 24 else rng.randint(7, 20)
                created = self.end - timedelta(days=age)
                geo = 1 if rng.random() < 0.7 else 0
                url = f"https://news.example.invalid/{cc.lower()}/{i}-{m['model_key']}"
                conn.execute("""INSERT OR IGNORE INTO dynamics(brand_id,country_code,category_code,source_type,
                                    source_name,title,url,published_at,raw_text,summary_zh,tag,importance,
                                    url_hash,geo_named,created_at)
                                VALUES(?,?,?,'news',?,?,?,?,?,?,?,?,?,?,?)""",
                             (m["brand_id"], cc, m["category_code"], rng.choice(NEWS_OUTLETS),
                              t_es.format(**ctx), url, created.isoformat(), t_es.format(**ctx),
                              s_zh.format(**ctx), tag, imp + rng.choice([-1, 0, 0]), md5(url), geo,
                              f"{created.isoformat()} 09:00:00"))
                n += 1
            self.counts["dynamics"] = n
            n = 0
            for i in range(12):
                pid = rng.choice(self.rival_ids)
                m = self.rival_meta[pid]
                cc = rng.choice(COUNTRIES)
                sig, summ, impact, action = rng.choice(SIGNAL_TEMPLATES)
                ctx = dict(brand=m["brand"], model=m["model_name"], country_zh=COUNTRY_ZH[cc],
                           cat_zh=CAT_ZH[m["category_code"]])
                d = (self.end - timedelta(days=rng.randint(0, 12))).isoformat()
                conn.execute("""INSERT INTO strategy_signal(signal_date,country_code,brand_id,category_code,
                                    rival_product_id,signal_type,confidence,summary_zh,evidence,impact_zh,
                                    suggested_action,agent)
                                VALUES(?,?,?,?,?,?,?,?,?,?,?,'demo-synthetic')""",
                             (d, cc, m["brand_id"], m["category_code"], pid, sig,
                              round(rng.uniform(0.55, 0.92), 2), summ.format(**ctx),
                              json.dumps({"moves": rng.randint(2, 9), "window_days": 14}),
                              impact.format(**ctx), action.format(**ctx)))
                n += 1
            self.counts["strategy_signal"] = n

    # ------------------------------------------------ reviews / VOC

    def voc(self, db) -> None:
        rng = self.rng
        n_rev = n_asp = n_prof = n_ins = 0
        prods = [pid for pid in self.rival_ids if pid in self.urls_by_product]
        chosen = sorted(rng.sample(prods, min(22, len(prods))))
        with db.tx() as conn:
            for pid in chosen:
                m = self.rival_meta[pid]
                cat = m["category_code"]
                launch = date.fromisoformat(m["global_launch_date"])
                bias = rng.uniform(-0.15, 0.25)         # some products just review better
                for url, cc, ch_id in self.urls_by_product[pid][:2]:
                    total = rng.randint(30, 900)
                    lang = LANG.get(cc, "es")
                    k = rng.randint(8, 22)
                    ratings = []
                    per_product_cc = {"pos": [], "neg": []}
                    for j in range(k):
                        days_after = rng.randint(3, min(400, max(4, (self.end - launch).days)))
                        rd = launch + timedelta(days=days_after)
                        if rd > self.end:
                            rd = self.end - timedelta(days=rng.randint(0, 30))
                        pool = [s for s in SNIPPETS if s[0] in _aspects_for(cat)]
                        # retail reviews skew positive: ~70% of picks come from the positive pool
                        pos_pool = [s for s in pool if s[1] == "positive"]
                        neg_pool = [s for s in pool if s[1] != "positive"]
                        picks = []
                        for _ in range(rng.randint(1, 3)):
                            src = pos_pool if (rng.random() < 0.7 + bias / 2 and pos_pool) else neg_pool
                            cand = [s for s in src if s not in picks]
                            if cand:
                                picks.append(rng.choice(cand))
                        pos = sum(1 for p in picks if p[1] == "positive") + bias
                        neg = sum(1 for p in picks if p[1] == "negative")
                        sentiment = "positive" if pos > neg else "negative" if neg > pos else "neutral"
                        rating = {"positive": rng.choice([4, 5, 5]), "neutral": rng.choice([3, 4]),
                                  "negative": rng.choice([1, 2, 2, 3])}[sentiment]
                        ratings.append(rating)
                        text = " ".join(p[3] if lang == "pt" else p[2] for p in picks)
                        zh = "".join(p[4] for p in picks)
                        h = md5(pid, url, j, text)
                        cur = conn.execute("""INSERT OR IGNORE INTO review(rival_product_id,channel_id,country_code,
                                    product_title,product_url,rating,title,content,content_zh,sentiment,aspects,
                                    author,review_date,helpful_count,is_verified,lang,content_hash,run_id)
                                VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
                                           (pid, ch_id, cc, f"{m['brand']} {m['model_name']}", url, rating, None,
                                            text, zh, sentiment, json.dumps([p[0] for p in picks]),
                                            f"Comprador {rng.randint(1000, 9999)}", rd.isoformat(),
                                            rng.randint(0, 40), 1 if rng.random() < 0.8 else 0, lang, h,
                                            self.run_ids[self.dates[-1]]))
                        rid = cur.lastrowid
                        if not rid:
                            continue
                        n_rev += 1
                        for p in picks:
                            frm = "aspect" if rng.random() < 0.8 else "review"
                            ins = conn.execute("""INSERT OR IGNORE INTO review_aspect(review_id,aspect_code,sentiment,sentiment_from)
                                                  VALUES(?,?,?,?)""",
                                               (rid, p[0], p[1] if frm == "aspect" else sentiment, frm))
                            n_asp += ins.rowcount if ins.rowcount > 0 else 0
                            (per_product_cc["pos"] if p[1] == "positive" else per_product_cc["neg"]).append(p[0])
                    avg = round(sum(ratings) / len(ratings), 2)
                    dist = {str(s): ratings.count(s) for s in range(1, 6)}
                    hot = total > 100
                    conn.execute("""INSERT OR IGNORE INTO review_profile(rival_product_id,channel_id,country_code,
                                        product_url,total_reviews,fetched_reviews,avg_rating,rating_dist,is_hot,
                                        hot_reason,last_fetched)
                                    VALUES(?,?,?,?,?,?,?,?,?,?,?)""",
                                 (pid, ch_id, cc, url, total, k, avg, json.dumps(dist), 1 if hot else 0,
                                  ("促销期间成交量大，评论集中在价格与续航" if hot else None),
                                  f"{self.dates[-1]} 10:00:00"))
                    n_prof += 1
                    praise = sorted(set(per_product_cc["pos"]), key=per_product_cc["pos"].count, reverse=True)[:3]
                    compl = sorted(set(per_product_cc["neg"]), key=per_product_cc["neg"].count, reverse=True)[:3]
                    conn.execute("""INSERT OR IGNORE INTO voc_insight(rival_product_id,country_code,period_start,
                                        period_end,review_count,avg_rating,praise_points,complaint_points,
                                        watch_signals,vs_acme,summary_zh)
                                    VALUES(?,?,?,?,?,?,?,?,?,?,?)""",
                                 (pid, cc, self.dates[0], self.dates[-1], k, avg,
                                  json.dumps([_ASPECT_ZH.get(a, a) for a in praise], ensure_ascii=False),
                                  json.dumps([_ASPECT_ZH.get(a, a) for a in compl], ensure_ascii=False),
                                  json.dumps(["售后响应慢" if "service" in compl else "无明显质量信号"], ensure_ascii=False),
                                  None,
                                  f"{m['brand']} {m['model_name']} 在{COUNTRY_ZH[cc]}的 {k} 条样本评论平均 {avg} 星："
                                  f"好评集中在{'、'.join(_ASPECT_ZH.get(a, a) for a in praise) or '整体体验'}，"
                                  f"差评集中在{'、'.join(_ASPECT_ZH.get(a, a) for a in compl) or '无'}。"))
                    n_ins += 1
        self.counts.update({"review": n_rev, "review_aspect": n_asp, "review_profile": n_prof,
                            "voc_insight": n_ins})

    # ------------------------------------------------ derived by the app itself

    def matches(self, db) -> None:
        from app.matching import CompetitorMatcher
        r = CompetitorMatcher().rebuild_all()
        self.counts["competitor_match"] = r.get("matches", 0)
        if r.get("warning"):
            print("  matcher:", r["warning"])

    def watch_and_alerts(self, db, trends) -> None:
        rng = self.rng
        cands = trends.suggest_watch(10)
        picked = cands[:2]
        for i, p in enumerate(picked):
            trends.add_watch("product", p["id"], "", "P0" if i == 0 else "P1",
                             note="demo: closest rival in our main phone band")
        trends.add_watch("brand", rng.choice(RIVAL_BRANDS), "", "P1", note="demo: brand-level watch")
        trends.add_watch("category", "phone", "MX", "P2", note="demo: MX phone band")
        r = trends.scan_alerts(days=14)
        self.counts["watchlist"] = len(trends.watchlist())
        self.counts["price_alert"] = r.get("fired", 0)

    def weekly(self, db) -> None:
        from app.agents.weekly import WeeklyReportAgent
        made = 0
        for back in (7, 0):
            anchor = (self.end - timedelta(days=back)).isoformat()
            try:
                r = WeeklyReportAgent(llm=None).run(week_start=anchor, brief=True)
                if r.get("report_id"):
                    made += 1
            except Exception as e:                       # noqa: BLE001
                print(f"  ! weekly brief for {anchor} failed: {type(e).__name__}: {e}")
        if not made:
            with db.tx() as conn:
                conn.execute("""INSERT OR IGNORE INTO weekly_report(week_start,week_end,scope,title,content_md,highlights,metrics)
                                VALUES(?,?,?,?,?,?,?)""",
                             (self.dates[-7], self.dates[-1], "all", "Demo weekly brief",
                              "# Demo weekly brief\n\nSynthetic data - see tools/make_demo_db.py.",
                              json.dumps([]), json.dumps({})))
            made = 1
        self.counts["weekly_report"] = made


def _aspects_for(cat: str) -> set[str]:
    from app import voc_aspects
    return set(voc_aspects.for_category(cat))


try:
    from app import voc_aspects as _va
    _ASPECT_ZH = dict(_va.ASPECT_ZH)
except Exception:                                        # noqa: BLE001
    _ASPECT_ZH = {}


# ---------------------------------------------------------------- main

def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Fill the app database with a synthetic demo dataset.")
    ap.add_argument("--seed", type=int, default=20260901, help="RNG seed (default 20260901)")
    ap.add_argument("--days", type=int, default=60, help="days of daily observations (default 60)")
    ap.add_argument("--end", default=None, help="last observation date YYYY-MM-DD (default: today)")
    ap.add_argument("--fresh", action="store_true", help="delete data/intel.db before building")
    args = ap.parse_args(argv)

    end = date.fromisoformat(args.end) if args.end else date.today()

    made = ensure_config_files()
    for p in made:
        print(f"created {p}")

    from app import config, db, products, trends   # noqa: E402  (after config files exist)

    if args.fresh:
        for suffix in ("", "-wal", "-shm"):
            p = Path(str(config.DB_PATH) + suffix)
            if p.exists():
                p.unlink()
        print(f"removed {config.DB_PATH}")

    db.init_db()
    existing = db.q1("SELECT COUNT(*) c FROM price_obs")["c"]
    if existing:
        print(f"database already holds {existing} price observations: {config.DB_PATH}")
        print("re-run with --fresh to rebuild the demo dataset from scratch")
        return 1

    print(f"building synthetic dataset: seed={args.seed} days={args.days} end={end}")
    b = DemoBuilder(args.seed, end, args.days)
    print("[1/7] dimensions (brands, channels, fx)");   b.dims(db)
    print("[2/7] products");                            b.products(db, products)
    print("[3/7] daily price observations + moves");    b.observations(db)
    print("[4/7] launch events, intel feed, signals");  b.launches(db); b.intel(db)
    print("[5/7] reviews and aspect tags");             b.voc(db)
    print("[6/7] competitor matches, watchlist, alerts")
    b.matches(db); b.watch_and_alerts(db, trends)
    print("[7/7] weekly brief (facts-only, no LLM)");   b.weekly(db)

    print("\nrows written:")
    for k, v in b.counts.items():
        print(f"  {k:<18} {v}")
    print(f"\ndatabase: {config.DB_PATH}")
    print("next:     python main.py serve   ->  open http://127.0.0.1:8765")
    return 0


if __name__ == "__main__":
    sys.exit(main())
